### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by Jojoman632** [GPUOpen-LibrariesAndSDKs/Capsaicin#27]
Hi, I am new to CG. My Device Specs are Amd5800h rtx3060 Laptop. The console log shows "AMD Radeon" as selected device instead of 3060. I am experiencing total white screen.  Can Anyone help me fix it?

**Comment by maoliver-amd** [comment]
Currently the code is selecting the AMD GPU ahead of your other card. We have already improved the GPU detection logic in multi GPU systems which will attempt to choose the best card available. This will be included in the next upcoming release
