### ISSUE TITLE
CMake Failed

### ISSUE THREAD

**Issue by GuDuJian-J-Zhang** [GPUOpen-LibrariesAndSDKs/Capsaicin#4]
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
The C compiler identification is MSVC 19.29.30148.0
The CXX compiler identification is MSVC 19.29.30148.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Found Bash: C:/Program Files/Git/bin/bash.exe  
Looking for CL_VERSION_2_2
Looking for CL_VERSION_2_2 - not found
Looking for CL_VERSION_2_1
Looking for CL_VERSION_2_1 - not found
Looking for CL_VERSION_2_0
Looking for CL_VERSION_2_0 - not found
Looking for CL_VERSION_1_2
Looking for CL_VERSION_1_2 - not found
Looking for CL_VERSION_1_1
Looking for CL_VERSION_1_1 - not found
Looking for CL_VERSION_1_0
Looking for CL_VERSION_1_0 - not found
Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
Found Vulkan: C:/VulkanSDK/1.3.239.0/Lib/vulkan-1.lib  
Found Perl: C:/Strawberry/perl/bin/perl.exe (found version "5.32.1") 
  AVX2 backend     - ON
  SSE4.1 backend   - OFF
  SSE2 backend     - OFF
  NEON backend     - OFF
  NONE backend     - OFF
  NATIVE backend   - OFF
  Decompressor     - OFF
  No invariance    - OFF
  Diagnostics      - OFF
  ASAN             - OFF
  Unit tests       - OFF
Performing Test COMPILER_HAS_DEPRECATED_ATTR
Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
Performing Test COMPILER_HAS_DEPRECATED
Performing Test COMPILER_HAS_DEPRECATED - Success
Configuring done
CMake Error at src/core/CMakeLists.txt:109 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_RUNTIME_DLLS:core>

  Expression did not evaluate to a known generator expression

CMake Error at src/core/CMakeLists.txt:109 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_RUNTIME_DLLS:core>

  Expression did not evaluate to a known generator expression

CMake Error at src/core/CMakeLists.txt:109 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_RUNTIME_DLLS:core>

  Expression did not evaluate to a known generator expression

CMake Error at src/core/CMakeLists.txt:109 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_RUNTIME_DLLS:core>

  Expression did not evaluate to a known generator expression

CMake Error at src/core/CMakeLists.txt:109 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_RUNTIME_DLLS:core>

  Expression did not evaluate to a known generator expression

CMake Error at src/core/CMakeLists.txt:109 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_RUNTIME_DLLS:core>

  Expression did not evaluate to a known generator expression

CMake Error at src/core/CMakeLists.txt:109 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_RUNTIME_DLLS:core>

  Expression did not evaluate to a known generator expression

CMake Error at src/core/CMakeLists.txt:109 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_RUNTIME_DLLS:core>

  Expression did not evaluate to a known generator expression

CMake Error:
  Error evaluating generator expression:

    $<TARGET_RUNTIME_DLLS:scene_viewer>

  Expression did not evaluate to a known generator expression

CMake Error:
  Error evaluating generator expression:

    $<TARGET_RUNTIME_DLLS:scene_viewer>

  Expression did not evaluate to a known generator expression

CMake Error:
  Error evaluating generator expression:

    $<TARGET_RUNTIME_DLLS:scene_viewer>

  Expression did not evaluate to a known generator expression

CMake Error:
  Error evaluating generator expression:

    $<TARGET_RUNTIME_DLLS:scene_viewer>

  Expression did not evaluate to a known generator expression

Generating done

**Comment by GuDuJian-J-Zhang** [comment]
needs CMake3.21 or newer,  while mine is CMake3.19

**Comment by gboisse** [comment]
Thank you for reporting this. We have fixed this internally and will release it as part of the next version.

**Comment by maoliver-amd** [comment]
The latest verion 1.1 is now available with a variety of new features and bug fixes (including this one). This issue should be resolved in 1.1 so im closing it accordingly. If you still have any issue then feel free to reopen or post a new issue.
